### ISSUE TITLE
Excel results producing strange fields, e.g., '$/$3' or '$%$3'

### ISSUE THREAD

**Issue by jayatsandia** [sunspec/svp_energy_lab#17]
https://github.com/jayatsandia/svp_demo_oct_2018/blob/master/Scripts/curtailment_w_data_capture.py

**Comment by totallynotmeagain** [comment]
It does this on your system as well? So its not a regional settings issue?

**Comment by jayatsandia** [comment]
I haven't tested it here yet...

**Comment by totallynotmeagain** [comment]
Please do that. I have the suspicion that the mixed locale settings that were configured on that machine was the root of the problem. And if it is, the issue needs to be raised with XlsxWriter project

**Comment by jayatsandia** [comment]
It's a problem over here as well: 

Xdata ='CurtailmentRun_1.csv'!$A$2:$A$37
Ydata =CurtailmentRun_1.csv!$\$2:$\$37

I think that Estefan at CanmetENERGY figured something out about this. I'll ask him.

**Comment by EstefanCanmet** [comment]
My problem was around some script not importing correctly the result file ... ''import result as rslt" instead of ''from svpelab import result as rslt". For your problem Jay , do you have a results excel file example? What version of XlsxWriter are you using ?

**Comment by jayatsandia** [comment]
I tied to use ''import result as rslt" but it returned the following issue: 

2018-10-26 12:06:15.840  E  Test script exception: Traceback (most recent call last):
  File "D:\SVP\svp_demo_oct_2018-master\Scripts\curtailment_w_data_capture.py", line 179, in run
    result = test_run()
  File "D:\SVP\svp_demo_oct_2018-master\Scripts\curtailment_w_data_capture.py", line 161, in test_run
    rslt.result_workbook(excelfile, ts.results_dir(), ts.result_dir())
  File "svp\result.py", line 71, in result_workbook
  File "svp\result.py", line 246, in to_xlsx
  File "svp\result.py", line 517, in close
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 286, in close
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 500, in _store_workbook
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 1271, in _add_chart_data
  File "build\bdist.win32\egg\xlsxwriter\workbook.py", line 1330, in _get_chart_range
  File "build\bdist.win32\egg\xlsxwriter\utility.py", line 108, in xl_cell_to_rowcol
AttributeError: 'NoneType' object has no attribute 'group'

Attaching example excel file with the issue. Using whatever version of XlsxWriter is baked into SVP 1.5.9 

[Curtialment.xlsx](https://github.com/sunspec/svp_energy_lab/files/2520457/Curtialment.xlsx)

**Comment by EstefanCanmet** [comment]
The .xlsx isn't really useful...maybe the logging file in the .sunspec directory can help more to debug this issue since result.py prints almost all the processing steps.

xslxwriter version in SVP(1.5.9) is 0.6.6 . The latest is 1.1.2. 
Since this particular library is for data plotting , it might be useful to update it. To be discuss...

**Comment by totallynotmeagain** [comment]
Any update on this issue?

**Comment by jayatsandia** [comment]
No update from my side...

**Comment by EstefanCanmet** [comment]
Me neither ...

**Comment by EstefanCanmet** [comment]
I think I found the problem... 
In result.py replace ,
`(l.352) col_index = point_names.index(name)`
by 
`col = point_names.index(name`
and remove
`(l.353) col = xl_col(col_index)`
Also ,replace
`(l.367) values': '=%s!$%s$%s:$%s$%s' % (ws_name, col, 2, col, count + 1),`
by
`values': [ws_name, 2, col, count, col],`

Let me know if it works for you.

**Comment by totallynotmeagain** [comment]
@EstefanCanmet Please create a PR for your fix.
